service: aws-lambda

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1

functions:
  hello:
    handler: dist/handler.generateRandomNumber
    timeout: 60 # Seconds
    memorySize: 128 # MB
